version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/javafx-client"
    schedule:
      interval: weekly
    groups:
      client-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
