spring.application.name=SpringBoot-JWT-UserManagement
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/team_access_hub
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

demo.jwtSecret= ======================JWT=SECRET===========================
demo.jwtExpirationMs=86400000