demo.initializer.admin.username=${DEMO_ADMIN_USERNAME}
demo.initializer.admin.password=${DEMO_ADMIN_PASSWORD}
demo.initializer.admin.email=${DEMO_ADMIN_EMAIL}

demo.security.registration-enabled=${DEMO_REGISTRATION_ENABLED:true}
demo.security.swagger-enabled=${DEMO_SWAGGER_ENABLED:true}
